name: Validating AWS CFN with Security Policies

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Validate Policies
        run: |
          denied_policies=""
          for jsonfile in $(find . -type f -name "*.json"); do
            echo "Validating $jsonfile"
            result=$(opa eval -d aws_cloudformation_nist_800_53/ -i $jsonfile -f pretty 'data')
            if [[ $result != *"[]" ]]; then
              denied_policies="$denied_policies\n\n$result"
            fi
          done
          echo "$denied_policies" >> denied_policies.txt       
      
      - name: Read file
        id: read_file
        run: |
          echo "::set-output name=eval-result::$(cat denied_policies.txt | jq -R -s .)"

      - name: Create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.SOBALI_TOKEN }}
          title: Denied Policies
          body: ${{ fromJson(steps.read_file.outputs.eval-result) }}